"""add delivery zones, methods, order delivery fields

Revision ID: 2b42a4ee1aab
Revises: 207c39edf076
Create Date: 2026-09-07 14:35:59.353331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b42a4ee1aab'
down_revision: Union[str, Sequence[str], None] = '207c39edf076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PICKUP', 'COURIER', 'REGIONAL', name='deliverytype'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('eta_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['delivery_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('delivery_method_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('delivery_price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.create_foreign_key(None, 'orders', 'delivery_methods', ['delivery_method_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_price')
    op.drop_column('orders', 'delivery_method_id')
    op.drop_table('delivery_methods')
    op.drop_table('delivery_zones')
    # ### end Alembic commands ###
